/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author nisit
 */
public class InterfazLogrosMedallas extends javax.swing.JFrame {
    String nombre,passw;
    String datos="";
    /**
     * Creates new form Iniciar
     */
    public InterfazLogrosMedallas() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Panelg = new javax.swing.JPanel();
        ftper = new javax.swing.JLabel();
        editPerfBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logrostxt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        medallastxt = new javax.swing.JLabel();
        oroBB = new javax.swing.JLabel();
        plataBB = new javax.swing.JLabel();
        bonceBB = new javax.swing.JLabel();
        orotxt = new javax.swing.JLabel();
        platatxt = new javax.swing.JLabel();
        broncetxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(144, 215, 155));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelg.setBackground(new java.awt.Color(144, 215, 155));
        Panelg.setForeground(new java.awt.Color(144, 215, 155));
        Panelg.setPreferredSize(new java.awt.Dimension(825, 480));
        Panelg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ftper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Ellipse 1.png"))); // NOI18N
        Panelg.add(ftper, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 111, -1, -1));

        editPerfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Group 3.png"))); // NOI18N
        editPerfBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        editPerfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panelg.add(editPerfBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 260, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(164, 36));

        logrostxt.setBackground(new java.awt.Color(255, 255, 255));
        logrostxt.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        logrostxt.setText("LOGROS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(logrostxt)
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logrostxt)
                .addGap(22, 22, 22))
        );

        Panelg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 95, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(164, 36));

        medallastxt.setBackground(new java.awt.Color(255, 255, 255));
        medallastxt.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        medallastxt.setText("MEDALLAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(medallastxt)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medallastxt)
                .addGap(22, 22, 22))
        );

        Panelg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 95, -1, -1));

        oroBB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Group 24.png"))); // NOI18N
        Panelg.add(oroBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 168, -1, -1));

        plataBB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Group 23.png"))); // NOI18N
        Panelg.add(plataBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 260, -1, -1));

        bonceBB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Group 22.png"))); // NOI18N
        Panelg.add(bonceBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 352, -1, -1));

        orotxt.setText("0");
        Panelg.add(orotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 193, 37, -1));

        platatxt.setText("0");
        Panelg.add(platatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 283, 37, -1));

        broncetxt.setText("0");
        Panelg.add(broncetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 372, 37, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Cerrar Sesión");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Panelg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 27, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Group 36.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Panelg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 27, -1, -1));

        NOMBRE.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        NOMBRE.setText("NOMBRE");
        Panelg.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 275, -1, -1));

        getContentPane().add(Panelg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        InterfazIniciarCrearPerfil obj= new InterfazIniciarCrearPerfil();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        InterfazIniciar obj = new InterfazIniciar();
        obj.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogrosMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogrosMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogrosMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogrosMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogrosMedallas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JPanel Panelg;
    private javax.swing.JLabel bonceBB;
    private javax.swing.JLabel broncetxt;
    private javax.swing.JLabel editPerfBtn;
    private javax.swing.JLabel ftper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logrostxt;
    private javax.swing.JLabel medallastxt;
    private javax.swing.JLabel oroBB;
    private javax.swing.JLabel orotxt;
    private javax.swing.JLabel plataBB;
    private javax.swing.JLabel platatxt;
    // End of variables declaration//GEN-END:variables
}
