/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nisit
 */
public class MiniMenuPnl extends javax.swing.JPanel {

    /**
     * Creates new form MiniMenuPnl
     */
    public MiniMenuPnl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBtnPerfil = new javax.swing.JLabel();
        lblBtnMenu = new javax.swing.JLabel();
        lblBtnInicio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 217, 217));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setPreferredSize(new java.awt.Dimension(100, 90));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBtnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Perfil.png"))); // NOI18N
        lblBtnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblBtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnPerfilMouseClicked(evt);
            }
        });
        add(lblBtnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 56, 24));

        lblBtnMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu.png"))); // NOI18N
        lblBtnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnMenuMouseClicked(evt);
            }
        });
        add(lblBtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 35, 53, 24));

        lblBtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio.png"))); // NOI18N
        lblBtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnInicioMouseClicked(evt);
            }
        });
        add(lblBtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 56, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnPerfilMouseClicked
        InterfazLogrosMedallas obj = new InterfazLogrosMedallas();
        obj.setVisible(true);
        this.setVisible(false);
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnPerfilMouseClicked

    private void lblBtnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMenuMouseClicked
        InterfazMenú obj = new InterfazMenú();
        obj.setVisible(true);
        this.setVisible(false);
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnMenuMouseClicked

    private void lblBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnInicioMouseClicked
        InterfazIniciar obj = new InterfazIniciar();
        obj.setVisible(true);
        this.setVisible(false);
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnInicioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBtnInicio;
    private javax.swing.JLabel lblBtnMenu;
    private javax.swing.JLabel lblBtnPerfil;
    // End of variables declaration//GEN-END:variables
}
